name: macOS 11

# Dependencies of Glib package
env:
  MACOS_BREW: ${{ 'libxml2' }}

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  # macOS tasks
  build-mac-swift-latest:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: brew install $MACOS_BREW

      - name: Checkout SwiftLibXML
        uses: actions/checkout@v2
        with:
          path: SwiftLibXML

      - name: Build current SwiftLibXML
        run: |
          cd SwiftLibXML
          ./build.sh
          cd ..

      - name: Test SwiftLibXML
        run: |
          cd SwiftLibXML
          swift test
          cd ..

      - name: Remove unneeded files and archive artefacts
        run: | 
          cd SwiftLibXML
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-macos
          path: |
            SwiftLibXML/
          retention-days: 1
