name: Ubuntu 20.04

# Dependencies of this package
env:
  UBUNTU_APT: ${{ 'libxml2-dev' }}
  
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  # Ubuntu 20.04 tasks
  build-ubuntu-20_04-swift-latest:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout SwiftLibXML
        uses: actions/checkout@v2
        with:
          path: SwiftLibXML

      - name: Build current SwiftLibXML
        run: |
          cd SwiftLibXML
          ./build.sh
          cd ..

      - name: Test SwiftLibXML
        run: |
          cd SwiftLibXML
          swift test
          cd ..

      - name: Remove unneeded files and archive artefacts
        run: | 
          cd SwiftLibXML
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artefact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-20.04-5.3
          path: |
            SwiftLibXML/
          retention-days: 1
